### ISSUE TITLE
[Solved] question about non_max_supression function

### ISSUE THREAD

**Issue by Joaquin2000zz** [hugozanini/yolov7-tfjs#5]
hello! i have a doubt about why you decided to implement the non max suppression from scratch instead of using tf.image.nonMaxSuppression. my question is if you decided this for performance improvements or because you just wanted to do it. thanks in advance! and i hope you're well :DD

**Comment by hugozanini** [comment]
Hi, @Joaquin2000zz! I tested with the TensorFlow function and the performance was the same. So I decided to implement by myself as an exercise to better understand how non-max suppression works :)

**Comment by Joaquin2000zz** [comment]
Hello! Thank you for the reply. I see! Amazing job :DD It helped me tremendously to understand the non max supression! Thanks again!!
